spring:
  application:
    name: Popple
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/popple_db
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never
  upload:
    location: C://Users//WD//Desktop//popple
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    user:
      name: popple
      password: 960512

# jwt 토큰 발행 기초 설정
jwt:
    issuer: team-popple
    secret_key: secretofpopplesecretkeysungohkim
    access_duration: 1_800_000 # 1800000  # 30분 (30 * 60 * 1000)
    refresh_duration: 86_400_000 # 86400000 # 24시간 (24 * 60 * 60 * 1000)
oauth2:
  clients:
    google:
      client-id: 1060643141913-qg5cp9eff1ct5msu51ii7g5nkmvfo8rf.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://localhost:5173/oauth/google
      token-uri: https://oauth2.googleapis.com/token
      user-info-request-uri: https://www.googleapis.com/oauth2/v3/userinfo
    kakao:
      client-id: 5dfa43ae2f6f10ba8341535fddb93b59
      client-secret: kxVnvrkWHyYMkOarY9h8upoV8pJ0upxr
      redirect-uri: http://localhost:5173/oauth/kakao
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-request-uri: https://kapi.kakao.com/v2/user/me

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

